[package]
name = "immediate-mode"
version = "0.0.1"
authors = ["Gwen Lofman <Gwen@Lofman.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
